docker:
  path: .
id: 6ec7d286-d390-476a-adf3-a136a35c2c9e
name: samples_slack
resources:
  path: resources
streaming:
  filename: streaming.yaml
template: python
version: "0.3"
workflows:
  path: dags
  version: "2"
