docker:
  path: .
id: 750cfc58-bd16-4240-9cc6-3ce934fa2388
name: pyspark_streaming
resources:
  path: resources
streaming:
  filename: streaming.yaml
template: pyspark
version: "0.3"
workflows:
  path: dags
  version: "2"
