default:
  target: cloud
  outputs:
    cloud:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASS') }}"
      port: 5432
      database: "webinar"
      schema: "quality_coffee"
