default:
  target: coffee
  outputs:
    coffee:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USERNAME', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      database: "webinar"
      schema: "quality_coffee"

    conveyor:
      type: conveyor
      envVariables:
        POSTGRES_HOST:
          awsSSMParameterStore:
            name: "/conveyor-samples/postgres_host"
        POSTGRES_PASSWORD:
          awsSSMParameterStore:
            name: "/conveyor-samples/postgres_password"
