# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Gitpod config (browser open, workspace bin path)
    init: |
      mkdir -p /workspace/bin
      cat > /workspace/bin/open.sh <<EOF
      #!/bin/bash
      exec gp preview --external "$@"
      EOF
      chmod +x /workspace/bin/open.sh
    command: |
      sudo update-alternatives --install /usr/bin/www-browser www-browser /workspace/bin/open.sh 100
      echo "export PATH=\"/workspace/bin:\$PATH\"" >> ~/.bashrc
      exit
  - name: Install conveyor
    init: |
      tmpdir="$(mktemp -d)"
      cd $tmpdir
      wget https://app.conveyordata.com/api/info/cli/location/linux/amd64 -O conveyor_linux_amd64.tar.gz
      tar -zxvf conveyor_linux_amd64.tar.gz
      chmod +x bin/linux/amd64/conveyor
      mkdir -p /workspace/bin
      sudo install bin/linux/amd64/conveyor /workspace/bin/conveyor
      cd && rm -r $tmpdir
    command: exit
  - name: Install AWS CLI
    init: |
      tmpdir="$(mktemp -d)"
      cd $tmpdir
      wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip"
      unzip awscliv2.zip
      mkdir -p /workspace/aws-cli
      ./aws/install --install-dir /workspace/aws-cli --bin-dir /workspace/bin
      cd && rm -r $tmpdir
    command: exit

# Prebuild settings
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    main: false
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
