# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Uninstall lynx
    init: sudo apt-get remove lynx -y
  - name: Install AWS CLI
    init: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm awscliv2.zip
      rm -rf ./aws
    command: aws --version

  - name: Install Conveyor CLI
    init: |
      wget https://app.conveyordata.com/api/info/cli/location/linux/amd64 -O conveyor_linux_amd64.tar.gz
      tar -zxvf conveyor_linux_amd64.tar.gz
      chmod +x bin/linux/amd64/conveyor
      sudo cp bin/linux/amd64/conveyor /usr/local/bin/conveyor
      rm conveyor_linux_amd64.tar.gz
      rm -rf ./bin
    command: conveyor --version


# Prebuild settings
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    main: false
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false