AWSTemplateFormatVersion: 2010-09-09
Parameters: 
    OIDCProviderArn: 
        Description: The arn if oidc provider linked to the cluster
        Type: String
Resources:
    SampleBucket:
        Type: 'AWS::S3::Bucket'
        Properties:
            BucketName: !Join
                - "-"
                - - "datafy-samples"
                  - !Select
                        - 0
                        - !Split
                            - "-"
                            - !Select
                                - 2
                                - !Split
                                    - "/"
                                    - !Ref "AWS::StackId"
            AccessControl: BucketOwnerFullControl
            PublicAccessBlockConfiguration: 
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
    SampleBucketSSMParameter:
        Type: AWS::SSM::Parameter
        Properties: 
            Description: "Parameter containing the name of the s3 bucket"
            Name: "/datafy-samples/bucket/name"
            Type: String
            Value: !Ref SampleBucket
    SampleTaskRole:
        Type: 'AWS::IAM::Role'
        Properties:
            RoleName: "datafy-samples"
            Path: /
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Federated:
                            - !Ref OIDCProviderArn
                      Action:
                        - 'sts:AssumeRoleWithWebIdentity'
            Policies:
                - PolicyName: default
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                        - Effect: Allow
                          Action: 's3:*'
                          Resource:
                            - !Join
                                - ''
                                - - 'arn:aws:s3:::'
                                  - !Ref SampleBucket
                            - !Join
                                - ''
                                - - 'arn:aws:s3:::'
                                  - !Ref SampleBucket
                                  - /*
                        - Effect: Allow
                          Action: 'ssm:*'
                          Resource: 
                            - !Join
                                - ''
                                - - 'arn:aws:ssm:'
                                  - !Ref "AWS::Region" 
                                  - ':'
                                  - !Ref "AWS::AccountId" 
                                  - ':parameter/datafy-samples/*'