default:
  target: dev
  outputs:
    dev:
      type: athena
      database: awsdatacatalog
      schema: datafy_glue
      region_name: eu-west-1
      threads: 1
      s3_staging_dir: s3://datafy-training/openaq_dbt/
    test:
      type: athena
      database: awsdatacatalog
      schema: datafy_glue
      region_name: eu-west-1
      threads: 1
      s3_staging_dir: s3://datafy-training/openaq_dbt/

