docker:
  path: .
id: 43847ed8-30df-4bd8-8f5c-8a8dcbf0250c
name: openaq_pyspark
resources:
  path: resources
streaming:
  filename: streaming.yaml
template: ""
version: "0.3"
workflows:
  path: dags
  version: "2"
