CREATE DATABASE dlt_data;

--- create the role that will be assumed by dlt
use role accountadmin;

CREATE USER loader WITH PASSWORD='FILL_ME_IN';
CREATE ROLE DLT_LOADER_ROLE;

GRANT ROLE DLT_LOADER_ROLE TO USER loader;
GRANT USAGE ON DATABASE dlt_data TO DLT_LOADER_ROLE;
GRANT CREATE SCHEMA ON DATABASE dlt_data TO ROLE DLT_LOADER_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO DLT_LOADER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE dlt_data TO DLT_LOADER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE dlt_data TO DLT_LOADER_ROLE;


--- create the role used for verification purposes
CREATE ROLE DLT_READER_ROLE;
GRANT ROLE DLT_READER_ROLE TO USER <YOUR USER>;  -- improvement: grant this role to another dm-role. We're all grown-ups.
GRANT USAGE ON DATABASE dlt_data TO DLT_READER_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO DLT_READER_ROLE;
--- in case data is already loaded, use the next two lines...
GRANT ALL ON ALL schemas in database dlt_data to role DLT_READER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SH_FULL TO ROLE DLT_READER_ROLE;
--- ... in addition to these
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE dlt_data TO DLT_READER_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE dlt_data TO DLT_READER_ROLE;
