docker:
  path: .
id: 4efb538e-6083-44f5-88aa-20779a760028
name: samples-titanic
resources:
  path: resources
streaming:
  filename: streaming.yaml
template: ""
version: "0.3"
workflows:
  path: dags
  version: "2"
