data_source quality_coffee:
  type: postgres
  connection:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    catalog: webinar 
    schema: quality_coffee
