gateways:
  snowflake:
    connection:
      type: snowflake
      account: iqorzws-playground
      user: sqlmesh_demo_user
      password: 
      database: SQLMESH_DEMO_DB
      warehouse: COMPUTE_WH
      role: SQLMESH

default_gateway: snowflake

model_defaults:
  dialect: snowflake
  start: 2025-04-21
